require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

project 'COVIDSafePaths.xcodeproj',
'Debug-BT' => :debug,
'Debug-GPS' => :debug,
'Release-BT' => :release,
'Release-GPS' => :release,
'Staging-BT' => :release,
'Staging-GPS' => :release

def shared_pods
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"

  pod 'Realm', :modular_headers => true
  pod 'RealmSwift', :modular_headers => true
end

def bt_pods
  ### These should be removed in a future commit
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Alamofire', '~> 4.9.1'
  pod 'ZIPFoundation'
  pod 'Firebase/Crashlytics'
end

target 'BT' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  bt_pods
  shared_pods

  target 'BTTests' do
    inherit! :complete
    bt_pods
    shared_pods
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

